export const STOREFRONT_ASSETS = {
  khmerOrnament: "/ornaments/romdoul-kbach.png",
} as const;

export type StorefrontLanguage = "en" | "km";

export const STOREFRONT_COPY = {
  en: {
    search: "Search the menu...",
    allMenu: "All menu",
    menuCategories: "Menu categories",
    menuEyebrow: "Our menu",
    menuTitle: "Experience Cambodia",
    menuDescription:
      "More than a meal — a celebration of Khmer flavor, culture, and hospitality.",
    item: "item",
    items: "items",
    noImage: "No image available",
    noDishes: "No dishes found",
    menuComingSoon: "The menu is coming soon",
    adjustSearch: "Try adjusting your search or selecting another category.",
    noPublishedProducts: "This store has not published any products yet.",
    footerAttribution: "Powered by",
    storeInfo: "Store info",
    storeInfoFallback: "Everything you need to know about this store.",
    followUs: "Follow us",
    pricesDisplayedIn: "All storefront prices are displayed in",
    customizeDish: "Customize your dish",
    closeCustomization: "Close customization",
    required: "Required",
    optional: "Optional",
    upTo: "up to",
    chooseAtLeast: "Choose at least",
    from: "from",
    addToOrder: "Add to order",
    viewOrder: "View your order",
    startOrder: "Start your order",
    orderingForTable: "Ordering for table",
    yourOrder: "Your order",
    confirmItems: "Confirm your items before sending the order.",
    emptyOrder: "Select items from the menu to begin your order.",
    kitchenNote: "Note for the kitchen",
    kitchenNotePlaceholder: "No onion, less spicy…",
    total: "Total",
    sendingOrder: "Sending order…",
    placeOrder: "Place order",
    addItems: "Add items to place order",
    orderReceived: "Order received",
    invoiceSent: "Your invoice has been sent to the restaurant.",
    invoice: "Invoice",
    table: "Table",
    orderMore: "Order more items",
    specialOffer: "A special offer from",
    closePromotion: "Close promotion",
    exploreMenu: "Explore the menu",
  },
  km: {
    search: "ស្វែងរកក្នុងម៉ឺនុយ...",
    allMenu: "មុខម្ហូបទាំងអស់",
    menuCategories: "ប្រភេទមុខម្ហូប",
    menuEyebrow: "ម៉ឺនុយរបស់យើង",
    menuTitle: "បទពិសោធន៍រសជាតិកម្ពុជា",
    menuDescription:
      "លើសពីអាហារមួយពេល — ជាការអបអរសាទររសជាតិ វប្បធម៌ និងបដិសណ្ឋារកិច្ចខ្មែរ។",
    item: "មុខ",
    items: "មុខ",
    noImage: "មិនមានរូបភាព",
    noDishes: "រកមិនឃើញមុខម្ហូប",
    menuComingSoon: "ម៉ឺនុយនឹងមកដល់ឆាប់ៗនេះ",
    adjustSearch: "សូមកែពាក្យស្វែងរក ឬជ្រើសរើសប្រភេទផ្សេង។",
    noPublishedProducts: "ហាងនេះមិនទាន់បានបង្ហោះមុខម្ហូបទេ។",
    footerAttribution: "ដំណើរការដោយ",
    storeInfo: "ព័ត៌មានហាង",
    storeInfoFallback: "ព័ត៌មានសំខាន់ៗអំពីហាងនេះ។",
    followUs: "តាមដានយើង",
    pricesDisplayedIn: "តម្លៃទាំងអស់បង្ហាញជា",
    customizeDish: "ជ្រើសរើសបន្ថែម",
    closeCustomization: "បិទការជ្រើសរើស",
    required: "តម្រូវឱ្យជ្រើស",
    optional: "ជាជម្រើស",
    upTo: "អតិបរមា",
    chooseAtLeast: "សូមជ្រើសយ៉ាងតិច",
    from: "ពី",
    addToOrder: "បន្ថែមទៅការកុម្ម៉ង់",
    viewOrder: "មើលការកុម្ម៉ង់",
    startOrder: "ចាប់ផ្តើមកុម្ម៉ង់",
    orderingForTable: "កុម្ម៉ង់សម្រាប់តុ",
    yourOrder: "ការកុម្ម៉ង់របស់អ្នក",
    confirmItems: "សូមពិនិត្យមុខម្ហូបមុនពេលផ្ញើការកុម្ម៉ង់។",
    emptyOrder: "សូមជ្រើសរើសមុខម្ហូបដើម្បីចាប់ផ្តើមកុម្ម៉ង់។",
    kitchenNote: "កំណត់ចំណាំសម្រាប់ផ្ទះបាយ",
    kitchenNotePlaceholder: "មិនដាក់ខ្ទឹម កាត់ហឹរ…",
    total: "សរុប",
    sendingOrder: "កំពុងផ្ញើការកុម្ម៉ង់…",
    placeOrder: "ផ្ញើការកុម្ម៉ង់",
    addItems: "បន្ថែមមុខម្ហូបដើម្បីកុម្ម៉ង់",
    orderReceived: "បានទទួលការកុម្ម៉ង់",
    invoiceSent: "វិក្កយបត្ររបស់អ្នកត្រូវបានផ្ញើទៅភោជនីយដ្ឋាន។",
    invoice: "វិក្កយបត្រ",
    table: "តុ",
    orderMore: "កុម្ម៉ង់បន្ថែម",
    specialOffer: "ប្រូម៉ូសិនពិសេសពី",
    closePromotion: "បិទប្រូម៉ូសិន",
    exploreMenu: "មើលម៉ឺនុយ",
  },
} as const;

export const STOREFRONT_PALETTE = {
  light: {
    background: "#F8F3E8",
    card: "#FFFDF8",
    text: "#1B1B1B",
    muted: "#7A6A52",
  },
  dark: {
    background: "#111A14",
    card: "#19231C",
    text: "#F8F3E8",
    muted: "#B9AA91",
  },
} as const;
